<?php
	define( 'TWITTER_CONSUMER_KEY', 'ENTER-YOUR-CONSUMER-KEY' );
	define( 'TWITTER_CONSUMER_SECRET', 'ENTER-YOUR-CONSUMER-SECRET' );
	define( 'TWITTER_ACCESS_TOKEN', 'ENTER-YOUR-ACCESS-TOKEN' );
	define( 'TWITTER_ACCESS_TOKEN_SECRET', 'ENTER-YOUR-ACCESS-TOKEN-SECRET' );

?>